ShipBit/wingman-ai

configs/system/config.example.yaml, wingmen/open_ai_wingman.py
fixes https://github.com/ShipBit/wingman-ai/issues/64
The config structure was changed from:
```yaml
elevenlabs: Adam
```
to
```yaml
elevenlabs: 
name: Adam
id: xyz # if you want to use an id
```
The OpenAiWingman base now validates that either `voice.name` or `voice.id` are present in the config. 
If **both** are set, `id` takes precedence over `name.`
=> 64 Global elevenlabs voice config overrides Wingman elevenlabs config | Breaks app

api/interface.py, configs/system/config.example.yaml, wingmen/star_head_wingman.py
BREAKING CHANGE: 
Custom Wingman now have to define custom config entries in `custom_properties`. These can only be strings, so if you want to use numbers etc. you have to parse them manually in your custom wingman. 
This change is required because otherwise our schema generation for the WingmanConfig class will break and just say it's a generic dictionary.
=> fix schema generation

services/audio_recorder.py
This enables easier use of a local whispercpp server should it ever be included within wingman itself or if a user wants to use a whispercpp server instead of using azure or openai paid cloud services (default whispercpp server only supports 16000 audio, though it will also autoconvert at the cost of increased latency) 
When making this change to other repos in the past I have seen no downsides. File size also remains smaller this way.
=> Change audio recorder to use 16000 sample rate

api/enums.py, api/interface.py, configs/system/config.example.yaml, providers/xvasynth.py, services/config_manager.py, wingmen/open_ai_wingman.py
Add support for XVASynth, a free program on steam for which people have trained and shared various voices from video games, as a Wingman TTS provider.
https://github.com/ShipBit/wingman-ai/assets/87204721/cca8686d-2fb2-4bf6-bbbb-28fc4865f1f9
V3 voices are supported in this implementation.  This PR allows the setting of global settings for xvasynth as a tts provider or to override those settings on a wingman-by-wingman basis like other speech providers. So you could have one xvasynth voice for one wingman and a different xvasynth voice for another.
Ideally the user starts XVASynth before starting wingman ai if they intend to use the program, but if they fail to do so, wingmanai will try to start xvasynth at the path the user has provided for the program.
I'm not sure whether xvasynth works …
=> XVASynth TTS support

configs/system/config.example.yaml, wingmen/wingman.py
-more testing revealed mouse relative input was not working as expected on windows. Changed to manually computing relative position and moving mouse instead
-further documentation review revealed how to get write function to work properly on windows to type capital letters and special characters, before it would only type lower case
-fixed some of the sample commands based on a community member's input (missile command and most used debug display info command) and also fixed typos in same (Turret Up/Down)
=> New input functionality misc fixes

api/interface.py, wingmen/open_ai_wingman.py, wingmen/wingman.py
Fixes:
- create dummy tool responses that get updates throughout the process to prevent history corruption
- automated message rearrangement if all tool calls are finished and message is no longer the newest one (this way the summarize gpt call will summarize the correct request)
- discard gpt calls if a new one started before it finished to prevent doubled tool calls / actions
- change config wait time type from int to float
- fix remember messages to retain the actual configured amount (was always one to many)
- Prevent "None" responses getting printed out
=> Prevent message history corruption and other small fixes

wingmen/open_ai_wingman.py
fix:
- revert remember messages count fix, as incorrect and causing issues when `remember_messages` is not set at all.
Did an oopsie there yesterday.
The function actually worked as expected, I just checked at the wrong "time" in the code yesterday.
Apart from that, this "fix" was also causing issues, if this was not set in the config, because the substraction happened before the check if it is a None-type.
So please merge this to get rid of this small change from yesterday :)
=> revert remember messages count fix, as incorrect and causing issues

requirements.txt, wingmen/wingman.py
fixes bug with relative mouse movement, so revert back to key_module.move() function for relative mouse movement commands.
=> update pydirectinput-rgx to version 2.1.1

api/enums.py, api/interface.py, configs/templates/defaults.yaml, providers/whispercpp.py, services/config_manager.py, wingmen/open_ai_wingman.py
-Add support for whispercpp server as a free local stt provider (https://github.com/ggerganov/whisper.cpp/releases)
-Allow user to configure variables to path to their whispercpp server.exe and chosen model and allow wingman ai to attempt to autostart the program to reduce friction, otherwise expect user to start server on their own
-Tested with Windows 11, not tested on MacOS
=> Whispercpp stt provider support

configs/templates/_Star Citizen/Computer.template.yaml, wingman_core.py
Added a force instant activation to star citizen template's self destruct command.
This does make sense, as it can be a critical error, if activated by AI on accident.
Attention: This also includes #131 as this is based on my develop branch and I didn't move that old one into its own branch back when I created that PR. Sorry.
=> Add force instant activation to star citizen self destruct

api/enums.py, api/interface.py, keyboard/keyboard/__init__.py, keyboard/keyboard/_darwinkeyboard.py, keyboard/keyboard/_keyboard_event.py, keyboard/keyboard/_nixkeyboard.py, keyboard/keyboard/_winkeyboard.py, services/command_handler.py, wingmen/wingman.py
Keyboard actions in the config have optional `release` and `press` flags added to them.
If none or both are set, they are executed as already known and hold time is taken into account.
If only `press` or `release` is set, only the specific action is triggered and the wait time in between keyboard actions basically becomes the hold time.
This allows key presses to sustain several different key presses in between.
But it will need some GUI implementation, as these recordings are currently not shown well.
Also it currently only triggers, when a macro recording is stopped with the `esc`-key.
If stopped with the "Stop recording"-button, it is recorded as currently known in the system.
Apart from that, I also enabled keyboard suppression on command recording. This allows all keys, including …
=> Add keyboard release and press options

api/interface.py, requirements.txt, services/settings_service.py, wingman_core.py
This PR changes how audio settings are saved.
From this
```
audio:
input: 1
output: 13
```
To this
```
audio:
input:
hostapi: 0
name: 'SteelSeries Sonar - Microphone '
output:
hostapi: 0
name: Name does not exist
```
Its also compatible with the old style and will rewrite it on first launch.
If no audio device setting is set up or the configured one is not found, system default will be used.
And there are also additional outputs at the start.
On server, input and output will always be printed out, like this:
And the client only shows the warnings, like this:
This should help to understand automated changes.
=> Audio settings based on name instead of index

wingmen/open_ai_wingman.py
-Add new function in open_ai_wingman which removes any instances of text in asterisks which is typically the AI emoting or narrating, and sounds weird to hear out loud
-Implemented only at the point the text will be sent to voice so that text-based chat will still contain the emote/narrated text for users who prefer to see that.
-Query whether there is anything else we should be removing?  Or should it be a user config what text to remove, if any?
=> Remove emote / narration text from verbal wingman responses

keyboard/keyboard/_winkeyboard.py
Just removed alt gr from the automated scan code mapping, as it is already mapped to scan code 541 manually later on.
This should prevent the default command "Flight Ready" with hotkey "alt gr" to get mapped to scan code "56", which is left alt, as the extended flag, which would prevent that, in the `map_name` function is not used at all.
But I have no idea why this has become an issue once more. 🤷‍♂️
=> Alt gr fix

wingman_core.py
What the title says.
Very simple adjustment to not check wingmen on key presses, that do not have a hotkey assigned to them.
This check was causing an error before, if not hotkey was set hot at least one wingman.
Reported by ManteMcFly on Discord:
https://discord.com/channels/1173573578604687360/1242028956132179978
=> fix hotkey detection with wingmen without hotkey

skills/skill_base.py
Just added a threading option to easily move processing into their own threads for skills.
This would be a first step. Afterwards I would like to edit all skills that currently use threading to utilize this central method instead.
=> providing a threaded execution option in skill base

skills/timer/main.py, skills/uexcorp/main.py, skills/voice_changer/main.py, templates/skills/timer/main.py, templates/skills/uexcorp/main.py, templates/skills/voice_changer/main.py
Moving thread execution from skills to skill base.
Gives cleaner code an a central position to adjust threading if ever needed.
Changelog:
- utilizing `threaded_execution` in uexcorp, voice changer and timer skills
=> moving thread generation from skills to skill base for cleaner code

skills/web_search/main.py, templates/skills/web_search/main.py
If user explicitly identifies a particular site, or infers a site that the AI has already identified, the AI can choose to do a deep dive on that single site and skip the general duckduckgo search.  Wait times and length of downloaded content are adjusted longer accordingly.
=> Web search single site functionality added

services/audio_recorder.py, wingman_core.py
As the title says.
Currently, when you start the wingman core but no mic is connected or a windows setting or anti-virus blocks mic access, the core will crash. Even the log shows no error.
As this happened multiple times now, I added a try catch block around the input streaming initializing with a handy error message.
This should prevent these unexpected untraceable crashes because of that in the future.
=> making Wingman AI resistant to inaccessible mics

services/sound_effects.py
Distortion is -required- on this  pedalboard so we can not remove it.  However, due to how pedalboard does its effect, -100 is absolutely off, +100 is insane levels of on.  I have moved closer to -100 on both low and medium quality to keep the base effect but make it less severe.
=> Distortion Flip to negatives to fix quality

skills/control_windows/default_config.yaml, skills/control_windows/main.py, templates/skills/control_windows/default_config.yaml, templates/skills/control_windows/main.py
not all applications support this but the ones that do can be snapped to the top, left, right and bottom of user screen
edge and chrome do not support this, but programs like powershell, notepad++ do
add debug logging and more try/except statements so users can figure out why sometimes things don't work
also list open applications, that may help wingman ai execute commands on problematic apps by ensuring the proper title is used
Note, with microsoft edge, sometimes once it is open, the window displays something like "Meta AI and 14 more pages - Personal - Microsoft\u200b Edge" as the title, and this messes up further commands with Edge, may want to also consider somehow stripping special characters like that to increase useablity.  Right now this just has a specific hack for Edge and the …
=> Provide support to snap applications

skills/skill_base.py, wingman_core.py, wingmen/wingman.py
Adding load (prepare) and unload event hooks for skills.
This is needed to allow skills to end background tasks, if they are no longer active.
Specifically for these skills:
- radio chatter
- voice changer
- timer
=> adding load (prepare) and unload events for skills

services/audio_recorder.py, services/settings_service.py, wingman_core.py
Added mic selection to `update_input_stream` function.
Added trigger to restart continuous listening on:
- audio device change
- va provider change
In total this should fix the issues where VA was using a different mic, than the PTT actions.
Info:
Azure is probably still an issue, as its using its own type of voice recognition.
But I'm not sure how to do the changes and testing them out, as I don't have direct Azure access.
This is probably also not a big issue right now, as I think that no one uses Azure right now.
But it should be added to some kind of known error/backlog list.
=> Fix VA mic selection

wingmen/wingman.py
Changelog:
- Adding `unload_skills` function to wingman
- Triggering `unload_skills` on `init_skills` if `self.skills` is not empty
This fixes double inits of skills (bad for threaded workloads) on a re-init due to a config change.
=> unload skills on init skills

providers/xvasynth.py
-extend timeout time; ten seconds was not enough to synthesize long paragraphs of text
-use try/except to catch errors so they don't freeze client
-overall xvasynth latency would benefit from a sentence by sentence streaming approach but that would likely make it extraordinarily complex to integrate with all the audio effects and other skills like radio chatter and voice changer, so leaving as-is for now.
=> Fixes bug where xvasynth would time out

.github/workflows/release.yml, .gitignore, api/interface.py, docs/develop-linux.md, docs/develop-macos.md, docs/develop-windows.md, main.py, providers/whispercpp.py, services/module_manager.py, services/settings_service.py, services/tower.py, templates/configs/defaults.yaml, templates/configs/settings.yaml, wingman_core.py, wingmen/open_ai_wingman.py, wingmen/wingman.py
whispercpp is now bundled in our installer package (Tauri/client side) so that we hopefully won't run in any Win Defender issues. This also has the benefit that uninstalling Wingman AI also deletes the whispercpp files.
I created this structure in the Wingman AI install dir:
- whispercpp (base non-CUDA whisper)
- whispercpp-cuda (CUDA whisper)
- whispercpp-models (used by both)
whispercpp is now basically a "fist-class-citizen" and handled similar to AudioPlayer: We create one instance of it very early and then pass it around to whoever needs it. The whispercpp class has been refactored to handle different tasks like starting/stopping the server (on Windows) etc. Autostart obviously only works on Windows. On MacOS, you have to start it manually. 
Dev docs have been updated but you can …
=> bundle whispercpp

main.py, services/config_manager.py, services/config_migration_service.py, services/config_service.py, services/file.py, services/printr.py, services/system_manager.py
Finally.. config migrations! 
I added a new `ConfigMigratonService` that allows us to dynamically add new migrations later by just adding a function like `def migrate_140_to_150(self)`. This function must provide 3 parts:
- `def migrate_settings(old: dict, new: SettingsConfig) -> dict`
- `def migrate_defaults(old: dict, new: NestedConfig) -> dict:`
- `def migrate_wingman(old: dict, new: Optional[dict]) -> dict:`
and finally it must call the parent `migrate` function like this:
```
self.migrate(
old_version="1_4_0",
new_version="1_5_0",
migrate_settings=migrate_settings,
migrate_defaults=migrate_defaults,
migrate_wingman=migrate_wingman,
)
```
The migration parts themselves are very simple and concentrate on the actual changes. The idea is that you take the `old` config and modify it so …
=> Config migrations

skills/ats_telemetry/main.py, templates/skills/ats_telemetry/main.py
-bug where if user started wingman with telemetry that had dispatch autostart on, then never started the game, then switched to another wingman, skill would keep looking to start the telemetry connection in the background
-Fixed by copying Jay's approach in radio chatter to ensure the skill is loaded before initiating the telemetry or starting the loop
=> fix fringe bug with ats_telemetry skill

keyboard/keyboard/__init__.py, keyboard/keyboard/_winkeyboard.py, skills/typing_assistant/main.py, templates/skills/typing_assistant/main.py
Adding compatibility mode to keyboard write function to prefer non-unicode inputs.
Changelog:
- added `hold` and `compatiblity` parameters to `keyboard.write`
- `compatiblity`-mode tries to do a non-unicode input where possible to support inputs in games.
- Default is set to True
- Added `yield_extended` flag to `winkeyboard.py`'s `map_name` function
- small code formatting fixes
- added 10ms hold and delay time in typing assistant skill
=> keyboard write compatibility improvements

skills/radio_chatter/main.py, skills/voice_changer/main.py, templates/skills/radio_chatter/main.py, templates/skills/voice_changer/main.py
Changelog:
- removing `error` parameter for `validate_and_set_wingman_pro` in radio chatter and voice changer skill
=> Fixing wingman pro initializing in skills

providers/elevenlabs.py, services/audio_player.py
Changelog:
- added `play_wav_sample` to audio player
- changed all occurences of `play_wav`, that try to play a sample, to `play_wav_sample`
This was an oversight on my end and now separates sample and normal wav playback.
=> fixing playback of wav audio samples

services/audio_library.py
Clear the playback finished callback before stopping playback. This ensures that the callback is not called after the playback has already been stopped, preventing potential issues.
Issues was, that after time x, when the playback would have finished, the finished callback was called again if the playback was manually stopped before. This let to a false status in the audio library if the same audio file was started again before the first playback would have finished.
=> Fix audio playback in audio library not stopping completely

skills/thinking_sound/main.py, templates/skills/thinking_sound/main.py
The auto_stop_playback method now correctly checks for both stream and raw_stream states instead of just the is_playing state. This ensures that the playback is properly detected and handled even in different streaming scenarios.
=> Fix playback condition in auto_stop_playback method

services/module_manager.py, wingmen/wingman.py
Changelog for skill discovery´(add skill dialog)
- Create a dict with all skills and their paths in appdata first
- Then run through the core skills folder and overwrite everything thats already in the dict.
Changelog for Wingman:
- removed a test exception in skill unload event from previous logging-PR
=> Fix appdata skill discovery

skills/uexcorp/default_config.yaml, skills/uexcorp/uexcorp/handler/config_handler.py, skills/uexcorp/uexcorp/helper.py, templates/skills/uexcorp/default_config.yaml, templates/skills/uexcorp/uexcorp/handler/config_handler.py, templates/skills/uexcorp/uexcorp/helper.py
Changelog:
- add uex skill config option `Update Hotwords`
- add sync function to get all names withing star citizen (locations, items, commodities and vehicles) and add them to the fasterwhisper hotlist.
- small code fix for authentication needed flag in config manager
=> Sync names from Star Citizen to fasterwhisper hotwords list

skills/uexcorp/main.py, skills/uexcorp/uexcorp/helper.py, templates/skills/uexcorp/main.py, templates/skills/uexcorp/uexcorp/helper.py, wingmen/open_ai_wingman.py, wingmen/wingman.py
This pull request introduces several changes to improve the initialization and validation processes for the UEXCorp skill. Key changes include handling multiple instances of the skill, adding error handling for invalid sessions, and ensuring proper cleanup of the helper instance.
Initialization and validation improvements:
* `skills/uexcorp/main.py` and `templates/skills/uexcorp/main.py`: Added a check to ensure only one instance of the UEXCorp skill is initialized at a time, setting `self.__invalid_session` to `True` if another instance is detected, and handling this invalid session in the `prepare`, `unload`, and `validate` methods. [[1]](diffhunk://#diff-fc994fbecdea22bf353398b8be432da7d4a44789140dadc02123d9a0e20092abR31-R56) [[2]](diffhunk://#diff-fc994fbecdea22bf353398b8be432da7d4a447 …
=> Add instance management and validation for UEXCorp skill initialization

services/printr.py
This pull request includes updates to the `services/printr.py` file to improve encoding handling and logging functionality. The most important changes include ensuring string encoding in the `write` method and specifying the encoding for the log file handler.
Enhancements to encoding and logging:
* [`services/printr.py`](diffhunk://#diff-a58100882acb6c2c3f2e985f45bf5956c5cd56c2bf6d70bf1f420cb96461cf55R25-R27): In the `write` method, added a check to ensure that strings are encoded in UTF-8 before being written to the stream.
* [`services/printr.py`](diffhunk://#diff-a58100882acb6c2c3f2e985f45bf5956c5cd56c2bf6d70bf1f420cb96461cf55L67-R71): In the `__new__` method, specified the encoding as 'utf-8' for the log file handler to ensure proper handling of character encoding in log files.
=> Fix encoding issues in StreamToLogger and set log file encoding to UTF-8

api/enums.py, services/config_migration_service.py, templates/configs/defaults.yaml
This pull request updates the `PerplexityModel` enum to reflect new model names, adjusts related configuration defaults, and ensures backward compatibility by migrating old settings to align with the updated models. Below are the most important changes grouped by theme:
* [`api/enums.py`](diffhunk://#diff-d4c95450ecbdde3edf5e9df76c7c09b35f3b0a98a947355e90099259cc3049feL84-R91): Replaced outdated model names in the `PerplexityModel` enum with new ones such as `SONAR_DEEP_SEARCH`, `SONAR_REASON_PRO`, and `R1_1776`. Updated the docstring link to reflect the new model documentation.
* [`templates/configs/defaults.yaml`](diffhunk://#diff-f52eca806b5f78e12e3bb6d2f058e6fb01ef1cff8f0864d75a2e254af25decc7L61-R61): Updated the default `conversation_model` for `perplexity` from …
=> Migrate models for Perplexity
