ShipBit/wingman-ai

wingmen/wingman.py

fixes #97 
As discussed here: https://discord.com/channels/1173573578604687360/1192112862030729246/1192126839242621009
```Simon: Okay, then I think your fix is fine. Could you create a GH issue and PR to fix it as you already did the work?```

fixing "None" playback on instant responses with non-instant commands

---

api/interface.py
configs/system/config.example.yaml
requirements.txt
wingmen/wingman.py

-add commands that should work for either directinput or pyautogui
-tested on windows, needs testing on mac
-if user enters primary, middle or secondary as the key for a command, will use left, middle, right mouse button clicks
-also supports hold commands with mouse clicks

implement mouse buttons, scroll, typewrite, multiple modifier keys, moveto and move (relative) inputs

---

wingmen/open_ai_wingman.py
wingmen/wingman.py

As discussed here: https://discord.com/channels/1173573578604687360/1188851241636347945
Added a bit of simple code to fix a tool call if the function name is a command name.

Add fix for false command calls by openai

---

api/interface.py
configs/templates/defaults.yaml
wingmen/open_ai_wingman.py

As discussed in discord. Added flag to exclude commands for GPT / force only instant activation:
`force_instant_activation`

Add force_instant_activation flag for commands

---

api/enums.py
main.py
providers/edge.py
providers/elevenlabs.py
providers/open_ai.py
providers/xvasynth.py
services/audio_player.py
services/sound_effects.py
services/tower.py
wingman_core.py
wingmen/open_ai_wingman.py
wingmen/star_head_wingman.py
wingmen/wingman.py

BREAKING CHANGE: Wingman ctor signature changed!
Custom Wingman now receive an AudioPlayer instance that they have to pass up to base Wingman.py.

BREAKING: AudioPlayer streaming

---

docs/develop-linux.md
wingmen/open_ai_wingman.py

`open_ai_wingman.py` had response spelled two different ways. My ide spell check was mad at me while I was working on some other changes XD

Starting Linux Documentation + Spelling fixes

---

api/interface.py
configs/templates/settings.yaml
services/audio_recorder.py
wingman_core.py

As discussed in discord.
If the recorded audio level in the frequency range from 85hz to 250hz is below a specified threshold, skip transcribe action.

VA voice detection filter

---

README.md
main.py
services/audio_player.py
services/config_service.py
services/pub_sub.py
services/settings_service.py
services/voice_service.py
wingman_core.py

This refactoring splits WingmanCore into several subclasses which define their own scoped endpoints. Core was getting to large and a place to "dump" endpoints into. 
New services:
- ConfigService
- SettingsService
- VoiceService
BREAKING: moved a lot of endpoint URLs

Core refactoring

---

skills/uexcorp/default_config.yaml
skills/uexcorp/main.py

Updated skill:
- bumped version to v11
- changed internal "DEV_MODE" to a file based logging system (`debug.log`)
- changed indent of cache file for human readability (`cache.json`)
- changed path of created files to `\skills\uexcorp\data` form `wingman_data\uexcorp`
- removed small chunks of not needed code
- removed "additional context" option (high cost, low use, therefore shouldn't be used anyway)

Uexcorp skill update

---

skills/voice_changer/main.py
templates/skills/voice_changer/main.py

Small fix for voice changer skill.
Changelog:
- fixed `get_prompt` function return

fix voice changer skill

---

services/config_manager.py

https://github.com/ShipBit/wingman-ai/issues/162

162 Default/logically deleted templates get recreated

---

skills/typing_assistant/credits.txt
skills/typing_assistant/default_config.yaml
skills/typing_assistant/main.py
templates/skills/typing_assistant/credits.txt
templates/skills/typing_assistant/default_config.yaml
templates/skills/typing_assistant/main.py

Adds basic skill to type what the user says, either a direct transcription or first using generative AI to create content and then type it, such as imagining the content for an email on the topic the user identfies and then typing it into an email program, typing a url from a recent web search into a browser, or responding to a chat message in discord.

implement typing assistant skill

---

skills/uexcorp/main.py
templates/skills/uexcorp/main.py

Small fix for the trade route parameters.
Changelog:
- fixed trade route tool calls required/optional parameter list

fix skill uexcorp

---

skills/quick_commands/main.py
templates/skills/quick_commands/main.py

Just some small fixes:
- renamed class name from `InstantActivationLearning` to `QuickCommands`
- fixed one function call of `_finish_learning` to make it async

fix skill quick commands

---

skills/uexcorp/default_config.yaml
skills/uexcorp/main.py
templates/skills/uexcorp/default_config.yaml
templates/skills/uexcorp/main.py
wingmen/open_ai_wingman.py

Updated the uexcorp skill to add ship buying information back in.
While on it, I also added a lore retrieval option, that uses the starcitizen wiki api.
Changelog:
- checking for game version change on start up
- retrieving all terminals, not just tradeports and therefore renaming all of them in the code
- getting ship buy and rent options and adding them to the terminal info for later output
- added starcitizen wiki lore retrieval (optional, default is off)

Skill uexcorp update to v13

---

skills/file_manager/main.py
templates/skills/file_manager/main.py

- increase max file size a bit
- add some additional safeguards to prevent errors when AI may use "" as a field for file name or directory name

File manager tweaks

---

skills/star_head/main.py
skills/timer/main.py
skills/voice_changer/main.py
templates/skills/star_head/main.py
templates/skills/timer/main.py
templates/skills/voice_changer/main.py

Updating some skills to utilize..
- `is_waiting_response_needed`
- `prepare`
- `unload`
.. events where needed.

Updating skills

---

skills/timer/main.py
templates/skills/timer/main.py

Changelog:
- adding loop functionality
- improving timer creation reliability
- moving time execution to one worker thread instead of a thread for each timer
- adding timer delay/loop changes as a new tool call
- better unload event handeling

Skill timer loops and improvements

---

skills/radio_chatter/default_config.yaml
skills/radio_chatter/main.py
templates/skills/radio_chatter/default_config.yaml
templates/skills/radio_chatter/main.py

Changelog:
- add radio effect selection
- make beep sound optional
- set volume preset to 0.5 from 0.4
This is a breaking change, if someone runs radio chatter from source, as the config changed.

Skill radio chatter updates

---

skills/control_windows/default_config.yaml
skills/control_windows/main.py
skills/file_manager/default_config.yaml
skills/file_manager/main.py
templates/skills/control_windows/default_config.yaml
templates/skills/control_windows/main.py
templates/skills/file_manager/default_config.yaml
templates/skills/file_manager/main.py

-Support saving AI-generated / imagined text to clipboard directly in control_windows (goes along with existing skill to read directly from clipboard)
-Support wider array of plain text files in file manager
-Support appending text to a file in file manager (user requested feature for "memory" type applications)

Make minor additions to control windows and file manager skills

---

skills/radio_chatter/main.py
templates/skills/radio_chatter/main.py

Changelog:
- utilize volume control in new config parameter for audio player

skill radio chatter utilize volume setting

---

services/audio_recorder.py
services/settings_service.py
wingman_core.py
wingmen/open_ai_wingman.py

Changelog:
- fix mixups of input and output devices
- fix setting new mic and only update input stream on changed mic
- Kinda unrelated, but important: Add unload overwrite to open_ai_wingman.py to clear dict. Otherwise tools are getting duplicated on each skill init

Fix audio device selection & skill unload

---

skills/file_manager/default_config.yaml
skills/file_manager/main.py
templates/skills/file_manager/default_config.yaml
templates/skills/file_manager/main.py

-now can save powershell scripts
-can open folders specified by the user in the gui (using same library as wingman_core.py)

Add open folder command, ps1 file extension to filemanager

---

skills/vision_ai/main.py
templates/skills/vision_ai/main.py

-allow users with debug mode on to see direct vision response from model to help in user understanding

minor change to print debug

---

api/enums.py
api/interface.py
providers/whispercpp.py
providers/xvasynth.py
services/config_manager.py
services/config_migration_service.py
services/module_manager.py
services/printr.py
services/settings_service.py
services/tower.py
services/voice_service.py
skills/radio_chatter/default_config.yaml
skills/radio_chatter/main.py
skills/voice_changer/default_config.yaml
skills/voice_changer/main.py
templates/configs/defaults.yaml
templates/configs/settings.yaml
templates/skills/radio_chatter/default_config.yaml
templates/skills/radio_chatter/main.py
templates/skills/voice_changer/default_config.yaml
templates/skills/voice_changer/main.py
wingman_core.py
wingmen/open_ai_wingman.py
wingmen/wingman.py

This PR introduces two new custom property types:
- voice_selection (with multiple option)
- slider (with min, max, step options)
The params are passed using the "options" field like this:
```yaml
- custom_properties:
- id: volume
options:
- label: min
value: 0
- label: max
value: 1
- label: step
value: 0.1
- id: voices
options:
- label: multiple
value: True (client re-saves this as "1" for unknown reasons)
```
While slider just writes back a number into `value`, the voice selection return type is a bit more complicated as it depends on the TTS provider and looks like this:
```yaml
- id: voices
options:
value:
- provider: wingman_pro
subprovider: azure
voice: en-US-AvaMultilingualNeural
- provider: wingman_pro
subprovider: azure
voice: en-US-EmmaMultilingualNeural
- provider: openai …
```

add new Custom Property types

---

skills/ats_telemetry/default_config.yaml
templates/skills/ats_telemetry/default_config.yaml

just tweak the default config a bit with some prompt engineering.

Minor ats telemetry tweak

---

providers/whispercpp.py
wingman_core.py

Catching timeout exception and adding check if transcription is available.

whisper.cpp timeout fix

---

api/commands.py
services/command_handler.py

Some fixes and improvements for the upcoming UI rework for commands

require keyboard command recording_type

---

skills/image_generation/default_config.yaml
skills/image_generation/main.py
templates/skills/image_generation/default_config.yaml
templates/skills/image_generation/main.py

-include toggle in config for whether to save or not
-images are saved to directory inside of skill folder.
-path is passed with function response for further use by the AI if image is saved.

add saving of images to image generation skill

---

skills/radio_chatter/main.py
templates/skills/radio_chatter/main.py

Changelog:
- check if generated messages are in the expected format and only then split for `:`

Make radio chatter generation more resilient to bad formatting.

---

services/command_handler.py

Changelog:
- On hotkey or normal macro mode recording if a mix of extended and not extended keys is pressed, the recording style will automatically change to advanced.
Info: In advanced mode, every keypress is its own action. Therefore we can save extended/non-extended flag individually.

Force advanced macro recording on mixed extended flag

---

services/module_manager.py
services/tower.py
skills/quick_commands/main.py
templates/skills/quick_commands/main.py
wingman_core.py
wingmen/wingman.py

Changelog:
- init `Tower` additionally with `config_dir` and `config_manager`
- init `Wingman` additionally with `tower`
- add `save_config` to `Wingman`
- add `save_wingman` to `Tower`
- use `save_config` in `Quick Commands` skill to actually save in file after learning event

Enable Wingmen to save themselves & Quick Commands update

---

main.py
services/printr.py
wingmen/open_ai_wingman.py
wingmen/wingman.py

Changelog:
- Remove color codes in log output
- add timestamp in log outputs
- add many try catch blocks throughout the application to prevent getting stuck on skill/AI errors
- reroute standard console output additionally to log file to catch everything in the log file

Better logging and error handling

---

skills/uexcorp/main.py
templates/skills/uexcorp/main.py

Changelog:
- rename tool parameter for ship information from `ship_name`/`ship_names` to `ship`/`ships` (seems to be more reliable)
- fix terminal dict to allow multiple terminals per nickname, as landing services and admin terminals share the same nickname at one location for example.
- add crew information to ship output

uexcorp skill fixes

---

skills/file_manager/default_config.yaml
skills/file_manager/main.py
templates/skills/file_manager/default_config.yaml
templates/skills/file_manager/main.py

Allow file manager to read supported file types (plain text and PDF) using the wingman's voice directly.

Update file manager to read files out loud in text to speech directly

---

skills/radio_chatter/main.py
templates/skills/radio_chatter/main.py

Changelog:
- fix Elevenlabs voice switch
- make chatter generation more robust with switching to JSON format

Small radio chatter skill update

---

api/interface.py
wingman_core.py
wingmen/open_ai_wingman.py

OpenRouter: omit tools if the model doesn't support them

---

skills/quick_commands/main.py
templates/skills/quick_commands/main.py
wingmen/open_ai_wingman.py
wingmen/wingman.py

This pull request includes several changes to improve type annotations, add new methods, and fix existing methods in the `wingmen` module. The most important changes include adding type annotations to various methods, introducing a new method to handle forced assistant command calls, and updating existing methods to handle new types.
Most importantly: When openai services or wingman pro services with a gpt model is used, the instant activated command will generate a "fake" tool call in the message history.
This will lead the AI to believe, that it "decided" to execute the command by the user request.
Doing this, prevents the AI from assuming that it's enough to confirm confirmation, instead of actually executing commands, as it did that before. (=Message history had no tool call)
* …

(Instant) Command improvements

---

skills/timer/main.py
templates/skills/timer/main.py

This pull request introduces significant changes to the `skills/timer/main.py` file, primarily focusing on refactoring the timer functionality and enhancing the timer's capabilities. The key changes include the introduction of the `ActualTimer` class, updates to various methods to accommodate the new class, and added support for silent timers.
* Introduced the `ActualTimer` class to encapsulate timer properties and methods, including initialization, property setters and getters, and utility methods.
* Updated the `__init__` method in the `Timer` class to use the `ActualTimer` class for managing timers.
* Modified the `start_timer_worker` and `execute_timer` methods to work with the `ActualTimer` instances, improving the readability and maintainability of the code. …

timer skill update

---

skills/ats_telemetry/main.py
templates/skills/ats_telemetry/main.py

-Needed to grab game type from telemetry data to use proper location finding function based on game

fix location data for ets2

---

api/enums.py
api/interface.py
providers/google.py
requirements.txt
templates/configs/defaults.yaml
wingman_core.py
wingmen/open_ai_wingman.py

- fetch models dynamically
- use OpenAI client and API to enable tool calls and full compatibility

Google Gemini update

---

api/interface.py
services/config_migration_service.py
services/websocket_user.py
templates/configs/settings.yaml
wingman_core.py

introduces new "Cancel TTS" aka "Shup up" hotkey. 
Configurable in Settings, defaults to Shift+y

implement new cancel TTS hotkey
